export const AUTH_USER_START = 'AUTH_USERT_START'
export const AUTH_USER_LOADING = 'AUTH_USERT_LOADING'
export const AUTH_USER_END = 'AUTH_USERT_END'
export const AUTH_USER_ERROR = 'AUTH_USERT_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';